services:
  - type: web
    name: boletim-escolar
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      npm install
      npm install @vitejs/plugin-react vite --save-dev
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    # Configurações de segurança e performance
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
    # Configurações de cache
    cache:
      - path: /assets/*
        ttl: 86400
      - path: /images/*
        ttl: 86400
    # Configurações de rede
    network:
      - port: 10000
        protocol: http
    # Configurações de recursos
    resources:
      cpu: 1
      memory: 1GB
      disk: 1GB
    # Configurações de monitoramento
    monitoring:
      errorThreshold: 5
      latencyThreshold: 1000 